version: '3'

services:

  json-server:
    image: clue/json-server
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./docker-files/mock_negative.json:/data/db.json

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    restart: always

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.4.0
    ports:
      - 5601:5601
    restart: always
    depends_on:
      - elasticsearch

  apm-server:
    image: elastic/apm-server:7.4.0
    ports:
      - 8200:8200
    restart: always
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    depends_on:
      - elasticsearch
      - kibana

  ambassador:
    image: quay.io/datawire/ambassador:0.72.0
    ports:
      - "81:80"
    volumes:
      - ./docker-files/ambassador.yaml:/ambassador/ambassador-config/ambassador.yaml
    environment:
      - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
    depends_on:
      - xpto-support

  xpto-support:
    image: xpto-support:0.0.0
    command: "--config=/app/config.json --port=5052"
    restart: always
    volumes:
      - ./docker-files/config.json:/app/config.json
    environment:
      - ELASTIC_APM_SERVICE_NAME=xpto-support
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - XPTO_PASSPHRASE=myCustomPassphraseToCryptData
    depends_on:
      - arangodb
